name: CI-CD

on: 
  push:
    branches: ["master"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.6.0

      #- name: Autenticação Azure
        #uses: Azure/login@v1.4.6
        #with: 
          #username: ${{secrets.DOCKERHUB_USER}}
          #password: ${{secrets.DOCKERHUB_PWD}}
      
      - name: Construção imagem Docker
        uses: docker/build-push-action@v4.1.1
        with: 
          context: ./TechChallenge2
          file: ./TechChallenge2/Dockerfile
          push: true
          tags: |
            techchallenge2/postech:v1
            techchallenge2/postech:latest

      - name: Executar testes
        run: |
          # Execute os testes unitários usando o XUnit
          dotnet test TechChallenge2.Tests/TechChallenge2.Tests.csproj
    
